[package]
name = "oriole_expat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Expat-compatible C interface to the Oriole XML parser"

[lib]
name = "oriole_expat"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
oriole.workspace = true
oriole_storage = { path = "../oriole_storage" }

[lints]
workspace = true
