from pathlib import Path
import hashlib,json,subprocess
root=Path('/tmp/oriole-cdata-finder-perf-handoff'); out=Path('/tmp/oriole-cdata-finder-perf-package-review.json'); j=json.loads(out.read_text()); sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest(); s=json.loads((root/'summary.json').read_text()); idx=json.loads((root/'files.json').read_text())
for r in idx['files']:
 p=root/r['path']; assert p.stat().st_size==r['bytes'] and sha(p)==r['sha256']
assert len(idx['files'])==9
notice=s['notice_sidecar']; p=root/notice['path']; assert sha(p)==notice['sha256']=='64293606655ef7918c7dac2d5de1ad1790b1935a6d06d5bdad4eceb71ebb8257'; assert p.read_bytes()==subprocess.check_output(['git','show',notice['git_origin']],cwd='/home/dev-user/code/oss/oriole-cdata-finder')
assert sha(root/'evidence.tar.gz')==j['archive_sha256'] and sha(root/'members.json.gz')==j['member_index_sha256']; assert not j['unbound_exclusions']
j['status']='passed'; j['findings']=[]; j['resolved_findings']=[notice['reason']]; j['notice_sidecar']=notice; j['top_files_sha256']=sha(root/'files.json'); j['summary_sha256']=sha(root/'summary.json'); j['readme_sha256']=sha(root/'README.md'); j['portable_verifier']={'sha256':sha(root/'verify.py'),'session':43441,'exit':0,'scope':'Executed with -I -S using only package-local files; every stored member and alias passed. Sidecar and new top-level hashes independently verified afterward.'}; j['review_attempts']={'first':'Stopped on required C upstream-notice coverage; no producer execution or result was changed. First reader/log retained.','second':'All archive/origin/coverage/exclusion checks passed; notice sidecar pending.','final':'Exact Git144 notice sidecar, new top-level index and unchanged archive/member-index readback passed.'}; j['reader_sha256']=sha('/tmp/oriole-cdata-finder-perf-package-review.py'); j['finalizer_sha256']=sha(__file__); out.write_text(json.dumps(j,indent=2)+'\n'); print('review',sha(out)); print('updated files',{r['path']:r['sha256'] for r in idx['files'] if r['path'] in ['README.md','summary.json','attach-notice.py',notice['path']]}); print('files.json',sha(root/'files.json'))
