[package]
name = "oriole_cli"
description = "A streaming XML checker powered by Oriole"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "oriole"
path = "src/main.rs"
doc = false

[features]
default = ["performance-allocator"]
performance-allocator = ["dep:tikv-jemallocator", "dep:mimalloc"]

[dependencies]
oriole.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { version = "0.1.50", features = ["v2"], optional = true }

[target.'cfg(all(not(target_os = "windows"), not(target_os = "openbsd"), not(target_os = "freebsd"), any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "powerpc64")))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[lints]
workspace = true
