from pathlib import Path
import collections,gzip,hashlib,json
out=Path('/tmp/oriole-upstream-final-values'); failures=json.loads((out/'failure-diagnostics.json').read_text()); audit=json.load(gzip.open('/home/dev-user/code/oss/oriole/tools/upstream-expat/results/2026-09-10/allocation-audit/audit.json.gz','rt')); old={r['test']:r for r in audit['tests']}; raised=json.loads((out/'allocation-raised512/results.json').read_text()); latest=collections.defaultdict(list)
for r in raised['results']:latest[r['test']].append(r)
facts={}
def add(names,category,reason,evidence=None):
 for name in names.split():
  assert name not in facts,name
  facts[name]={'category':category,'reason':reason,'evidence':evidence or ['Pinned upstream test body and final failed assertion']}
for name,rows in latest.items():
 if all(r['outcome']=='pass'for r in rows):
  add(name,'allocation_retry_ceiling','All 12 diagnostic contexts pass on the final release after raising only retry ceilings to512. Original assertions remain unchanged; original failure remains counted.',['allocation-raised512/results.json','prior allocation-audit/audit.json.gz'])
 else:
  reason=old[name]['reason']
  if name=='test_nsalloc_parse_buffer':reason='Earlier recoverable NO_BUFFER state defect is fixed. Current first failure is line129: after GetBuffer, test requires empty nonfinal ParseBuffer to allocate and fail with malloc disabled. Candidate initializes this path without a required allocation and succeeds. This is a fixed allocation-stage expectation, not the previously audited API-state defect.'
  if name=='test_alloc_nested_entities':reason='Test sets allocation budget12 to fail inside Expat nested storeEntityValue, then asserts child creation succeeds. Candidate exhausts budget while constructing child, which correctly returns NULL. Failure stage differs. The final unmodified test never reaches later value assertions; do not infer a parser defect or waive the failure.'
  add(name,'allocation_schedule_or_stage',reason,['allocation-raised512/results.json','prior allocation-audit/audit.json.gz'])
add('test_misc_alloc_create_parser_with_encoding','allocation_retry_ceiling','Upstream loops allowed allocation counts0..9 (exclusive10). Final candidate requires10 selected malloc calls; Expat requires5. Direct fail-count probe reaches successful creation at10 and observes zero live allocations after every failure/success.',['create_encoding_probe.py','create-encoding-probe.json'])
add('test_foreign_dtd_not_standalone','caller_policy_callback','Foreign DTD child is read, but candidate omits NotStandalone. If callback rejects, reference stops with22 before root content; candidate succeeds. Confirmed caller-policy gap; bounded isolated continuation fix in progress.',['foreign_expanded.py','foreign-expanded.json'])
add('test_empty_foreign_dtd','foreign_subset_state','Foreign DTD callback returns success without reading a child. Expat restores prior hasParamEntityRefs and rejects undefined entity11; candidate keeps possible subset and skips unknown entity. Absent handler and parsed-empty child are different states. Same bounded continuation fix as NotStandalone.',['foreign_expanded.py','foreign-expanded.json'])
add('test_ns_separator_in_uri','acceptance_or_api_contract','Candidate rejects xmlns URI containing colon when namespace separator is colon; Expat allows legacy URI-character separators. Both reject malicious non-URI separator collisions. Conservative over-rejection, not missing collision defense.',['namespace-separator-probe.json','Expat xmlparse.c addBinding separator whitelist'])
add('test_explicit_encoding','acceptance_or_api_contract','After parsing finishes, Expat permits XML_SetEncoding(NULL); candidate rejects because FFI state != initial. Mid-parse rejection is correct. Small finished-state setter compatibility gap.')
add('test_partial_char_in_epilog','acceptance_or_api_contract','Caller follows XML_Parse with XML_ParseBuffer(0,true) without a prior GetBuffer. Expat uses existing parser buffer and reports truncated character6; candidate returns NO_BUFFER42. Positive-length ParseBuffer still requires a reservation; any fix must preserve that contract.')
add('test_mem_api_unlimited','acceptance_or_api_contract','After setting allocator activation threshold0 before any input, Expat exempts public XML_MemMalloc/Realloc helpers from parser amplification checks and allocates1000/2000bytes. Candidate applies its tracker and returnsNULL. This is stricter helper-API scope, not an absent memory limit; current public calls are not exact Expat semantics.')
add('test_ext_entity_latin1_utf16le_bom test_ext_entity_latin1_utf16be_bom test_ext_entity_latin1_utf16le_bom2 test_ext_entity_latin1_utf16be_bom2','external_encoding_semantics','Explicit Latin1 external general-entity input treats BOM-looking bytes as ordinary Latin1 text in Expat; candidate rejects conflicting BOM19. Requires content-context decoder initialization; do not globally weaken document/DTD BOM checks.',['/tmp/oriole-encoding-classification-review.json'])
add('test_ext_entity_utf16_unknown','external_encoding_semantics','Unspecified external general-entity encoding: a\\0b\\0c\\0 remains UTF8 and rejects4 in Expat; candidate infersUTF16LE and acceptsabc. Expat allows leadingNUL BE and <NUL LE; fix must be context-sensitive. Real acceptance difference, no memory-safety failure observed.',['/tmp/oriole-encoding-classification-review.json'])
add('test_billion_laughs_attack_protection_api test_amplification_isolated_external_parser','documented_unsupported_api','Relative entity-amplification setters decline supported-value requests rather than configure Expat ratio accounting. Oriole uses documented absolute family/input/entity limits. Not a waiver and not evidence of missing resource-exhaustion defense.')
add('test_hash_salt_setter','documented_unsupported_api','Caller-provided 16-byte hash salt setter returnsfalse; parser uses its own hash implementation. Exact caller salt semantics are documented unsupported.')
add('test_misc_version','identity_api','Library reports Oriole identity/version rather than Expat2.8.4 exact XML_ExpatVersion string asserted by upstream.')
add('test_misc_expected_event_ptr_issue_980 test_byte_info_at_cdata','documented_input_context','XML_GetInputContext returnsNULL and XML_FEATURE_CONTEXT_BYTES=0 as documented. Upstream build config expects retained context bytes and asserts nonNULL before further callback/position assertions.')
add('test_misc_unknown_encoding_callbacks_protected test_unknown_encoding_success test_unknown_encoding_long_name_1','documented_custom_encoding','Tests return ASCII through multibyte converter callbacks. Candidate deliberately rejects ASCII aliases to retain XML lexical provenance. Callback safety assertions are not the failing assertion; parse success expectation fails at invalidtoken4.',['/tmp/oriole-encoding-classification-review.json','C README custom-encoding limits'])
add('test_long_utf8_character test_utf8_in_start_tags','documented_name_repertoire','Oriole implements XML1.0 FifthEdition NameStart ranges. Expat rejects U+10000 and case19 U+0901 as NameStart; candidate accepts valid FifthEdition names. Six contexts fail the latter loop; all remain counted.',['/tmp/oriole-encoding-classification-review.json'])
add('test_misc_input_2gb test_buffer_can_grow_to_max test_deep_nested_entity test_deep_nested_attribute_entity test_deep_nested_entity_delayed_interpretation','documented_absolute_limits','Tests exceed documented finite input/backing/nesting limits: 2GiB cumulative input, approximately1GiB ParseBuffer reservation, or10000-deep entity chains. Both default and raised runner limits retain same candidate failures. Reference succeeds under matched4GiB/15s bounds.')
add('test_reparse_deferral_is_inherited test_bypass_heuristic_when_close_to_bufsize','deferral_or_allocation_heuristic','Upstream asserts a specific delayed ElementDecl callback count or <4096 newly allocated bytes per fill after token completion. Candidate uses a different bounded incremental scanner and allocation layout. Exact deferral timing/allocation heuristic compatibility is documented; no proof of quadratic work follows from these assertions.')
add('test_byte_info_at_end','exact_position','Initial parser byteindex/count assertion fails (candidate initial index0 vs Expat-1); parsing acceptance is not the failed assertion.')
add('test_misc_async_entity_rejected','exact_position','Asynchronous entity is rejected with the expected error kind; upstream assertion fails on exact column. No acceptance regression established by this test.')
add('test_misc_deny_internal_entity_closing_doctype_issue_317 test_ns_invalid_doctype test_invalid_foreign_dtd test_not_utf16 test_external_entity_values test_bad_public_doctype test_bad_attr_desc_keyword test_bad_doctype test_bad_doctype_plus test_bad_doctype_star test_bad_doctype_query test_short_doctype','exact_error_diagnostic','Both reject at the observed failing assertion; exact error kind differs. For external-entity test, child diagnostic differs while parent failure remains external-handling21. Original test is still failed and may stop before later cases; this classification does not establish all later assertions.')
assert set(facts)==set(failures['counts']),(set(failures['counts'])-set(facts),set(facts)-set(failures['counts']))
rows=[]
for name in sorted(facts):
 row={'test':name,'failed_contexts':failures['counts'][name],**facts[name]};row['observed_diagnostics']=list(dict.fromkeys('\n'.join(r['diagnostics'])for r in failures['failures']if r['test']==name))
 if name in latest:row['current_retry512_diagnostic']={'passed':sum(r['outcome']=='pass'for r in latest[name]),'failed':sum(r['outcome']!='pass'for r in latest[name])}
 rows.append(row)
counts=collections.defaultdict(lambda:{'test_names':0,'failed_contexts':0})
for row in rows:counts[row['category']]['test_names']+=1;counts[row['category']]['failed_contexts']+=row['failed_contexts']
report={'scope':'First-failing-assertion classification of101 remaining failed public test names; no failure waived and no production-ready equivalence claim. Current matrix3621pass/1119fail; reference4740pass under matched4GiB/15s limits. All failed candidate contexts exit100, no signal/timeouts.','candidate_sha256':'f7e602e300daebedfc08854ed32adebeb656165cddc019dcc0b0226063f9f569','baseline_comparison':{'pass_to_fail':0,'fail_to_pass':166},'categories':dict(counts),'tests':rows,'recommendations':[{'priority':1,'fix':'Foreign DTD read acknowledgement and NotStandalone before EndDoctype/root','impact':'Restores configured rejection and undefined-entity handling; isolated fix authorized by root.'},{'priority':2,'fix':'External general-entity decoder initialization context','impact':'Closes acceptance difference for BOM-less ASCII/NUL UTF16LE and valid explicitLatin1 BOM-like input; preserve document/DTD handling.'},{'priority':3,'fix':'Small completed-parser/zero-length-buffer API compatibility','impact':'Permit documented finished-state SetEncoding and zero-length ParseBuffer finalization when internal input buffer exists; retain positive-length reservation checks.'},{'priority':4,'fix':'Finish DTD lexical error precedence and positions incrementally','impact':'Reduces diagnostic failures; lower priority than caller policy and decoded content semantics.'}],'allocation_note':'Fresh selected retry512 run620pass/64fail over684contexts; changes numeric retry ceilings only in old preserved C adapter and preloads exact final release, dladdr verified. This diagnostic never changes original3621/1119 passcount. Constructor extra probe: first success10 mallocs versus Expat5; original bound excludes10.','security_note':'No crash, timeout, memory-safety failure, or missing absolute limit established by remaining assertions. Caller-policy omission and external encoding interpretation are real compatibility risks. Independent allocator sweeps/ASan campaigns remain separate evidence.'}
(out/'failure-classification.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Remaining upstream failures','',report['scope'],'','| Classification | Test names | Failed contexts |','|---|---:|---:|']
for category,c in counts.items():lines.append(f"| {category.replace('_',' ')} | {c['test_names']} | {c['failed_contexts']} |")
lines+=['', '## Highest-impact follow-ups','']+[f"{r['priority']}. **{r['fix']}**: {r['impact']}" for r in report['recommendations']]+['',report['allocation_note'],'',report['security_note'],'','Per-test assertion evidence and exact classifications are in `failure-classification.json`.']
(out/'failure-classification.md').write_text('\n'.join(lines)+'\n');print(dict(counts)); print('total',sum(c['test_names']for c in counts.values()),sum(c['failed_contexts']for c in counts.values()))
